# About this exemplar assay

**A 12-plex febrile diseases immunoassay panel**

This set of methods is demonstrated through an exemplar: multiplexed immunoassay for evaluation of fever outcomes. This exemplar is designed to detect and quantify multiple immune and inflammation markers relevant to the study of febrile illness. It illustrates the complete workflow from marker selection, reagent preparation, and bead couplingthrough to data acquisition, analysis, and simulated prognostic modelling.

While the fever assay is used here as a working example, the concepts, methods, and code in this repository are applicable to the design and implementation of any multiplexed bead‑based immunoassay, for any set of biomarkers or analytes.

Fever has heterogeneous aetiology both within and between populations. With fever as a significant reason for health-seeking globally, understanding how clinical signs, symptoms and measurable factors could be used for prognosis and to establish aetiology could be a valuable tool in directing limited resources to where they are most needed.

Infectious causes of fever are a significant contributor to the case burden, but are both multitudinous and ecologically diverse. The fraction of fever cases which is attributable to a specific pathogen varies substantially with geography, climate and time; as well as in response to competing/co-endemic species and to human activities (which include public health & clinical interventions). Accurate clinical evaluation of fever cases therefore requires substantial knowledge of local and temporal epidemiological trends.

Flux in the prevalence of causative infections (i.e. because of seasonality or epidemics) means that the predictive value of any diagnostic algorithm or test is in a similar state of continuous change and is therefore prone to incompletely definable type 1 and type 2 errors. Misdiagnosis can occur because a clinician neither suspected, nor considered, the causative pathogen when making a diagnosis by clinical evaluation, or because of the opposite circumstance.

In some settings, the broad availability of laboratory-based or point-of-care tests can provide a more definitive, though still error-prone, diagnosis of specifically targeted (endemic) pathogens. In many settings which lack resources, access to diagnostics may be impossible, impractical or untimely. The complex aetiology of fever potentially requires the use of a plurality of diagnostic tests in each case. The inconsistent availability of such tests means that many or most fever cases ultimately remain undiagnosed and are treated syndromically.

When triaging a patient who presents with fever, one of the physician’s first tasks is likely to be an assessment of whether (in their regard) the patient is more likely to have a self-limiting disease, something severe enough to require hospital admission, or something in-between. The heterogeneity of febrile disease is such that whilst many cases require no treatment, or can be managed through an outpatient clinic; some are potentially fatal or life-changing. A key problem for the clinical triage is that some patients may appear at face-value to be relatively low-risk, but will still go on to die after being sent home to recover.

Immune markers have previously been used to prognosticate the outcomes of fever cases. Measuring molecules in the blood that are released by immune cells and the vascular endothelium during fever may not identify a specific cause of the fever, but can provide a non-specific measure of fever severity that provides insight into how a patient should be handled. Previous work has shown how such approaches can prognosticate on whether immune dysregulation will lead to a severe or non-severe outcome.

Signatures of an immune response have obvious potential to support clinical decision making by providing an objective and quantitative measure of disease severity which belies the subjectivity of a clinical assessment.  Being agnostic to the cause of the fever, measures of the severity of the immune response have the potential to act as a ‘catch-all’ triage tool, although the heterogeneous nature of fever causes means that an immune marker which performs well as a prognostic in one population may not be as effective in another population, or at another time.

The ability to detect multiple analytes in a single blood sample enables the identification of possible  markers of prognosis or association with particular outcomes or aetiologies. For translation to clinical use, the aim of multiplex analysis can be to screen a panel of severity markers in order to identify a single, best-performing, marker (for that population) that can then be incorporated into a rapid diagnostic test (RDT) or other point-of-care (POC) device.

Beyond its use as a screening tool, the use of platforms which can detect multiple analytes in parallel can build a more complex picture of the immune response to different pathogens or in different populations; and thus provide an immune ‘profile’. In some diseases and in some settings, these multifactor immune profiles may have synergistic value in discriminating, for instance, between fever cases which are caused by viruses or bacteria.

The ideal multiplex assay requires only a very small volume of analyte (in this case blood) to provide a large amount of information. This allows easier, less invasive, unified and cost-effective sampling and diagnostic testing. Dried blood spots (DBS) are a convenient way to sample, transport and store whole blood, particularly in low-resource settings. Other advantages of DBS have been highlighted and these refer to their use being minimally invasive (and as such better for repeated sampling of the same individual), lower cost and with a lower requirement for processing, storage and biosafety measures.

While commercial multiplex immunoassay kits are widely available, they do not necessarily include all analytes of interest (to a specific clinical context such as fever) on the same panel. This can lead to the need to test specimens on multiple panels, which can be very costly and which may not be feasible on very large sample sets due to cost, time or personnel constraints. In addition to this, commercial kits tend not to provide the option to use DBS samples, requiring initial experimentation and optimisation, and due to their proprietary components, can not be easily modified.

In this study, we developed and deployed a 12-plex bead-based antigen capture immunoassay on the Luminex MagPix platform. The assay we present uses only ‘off-the-shelf’ reagents and detects the following markers of immune and endothelial activation, selected for their association with fever prognosis, aetiology, or both: angiopoietins 1 and 2 (Ang-1, Ang-2); azurocidin (Azu); chitinase 3-like 1 (CHI3L1); interleukins 6, 8 and 10 (IL-6, IL-8, IL-10); interferon gamma inducible protein 10 (IP-10/CXCL-10); soluble tumour necrosis factor receptor 1 (sTNFR1); myxovirus resistance protein A (MxA); soluble triggering receptor expressed on myeloid cells (sTREM-1); TNF-related apoptosis-inducing ligand (TRAIL)

For those wishing to reproduce and use the fever panel, we fully detail reagent suppliers, product codes, laboratory protocols and instructions for optimisation and evaluation. For those wishing to develop their own immunoassays, the methods and code provide a framework on which to base such developments. We also provide an open-source data analysis pipeline (for use in R) which enables replication of our methods and reproduction of the figures and tables presented in the paper. If you want to try the analysis for yourself, you can find the input files in this repo <https://github.com/chrissyhroberts/Mos-Def>. For those aiming to develop these methods for other contexts and biomarkers, the generalisable workflow is open source and fully adaptable.
