---
title: "Specimen Testing"
---

# **Testing DBS samples with the biomarker assay**

**Reagents and materials needed**

-   All materials on the Shopping List.

-   Vortex mixer, sonicating waterbath, shaking platform, microfuge, pipettes and reservoirs.

-   PBS and PBS-TBN as per Buffers and Reagents protocol.

-   Coupled beads as per Bead Coupling protocol.

-   Detection antibodies as per Detection Antibody Prep.

### Lab worksheet protocol

Assay date \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ done by \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

**Aim**

To measure 12 immune markers in dried blood spot samples.

**Important notes**

DBS rehydrated 2 x 6 mm spots in 100 ul PBS-TBN+pi overnight.

All samples, standards & detection antibodies are **30 ul per well** volume.

Conduct your own Risk Assessment for the risks associated with your samples and handle accordingly.

Record date that standards were diluted and frozen on \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

**Sample plate IDs:** ...........................................................................................

**Assay overview and timings**

+------------------------------------------+--------+-------------------------------------------------+----------+-------------------------------------+----------+-------------------+----------+-------------+
| 12 beads coupled with capture antibodies | 1 wash | DBS eluate & previously frozen buffer standards | 3 washes | 12 biotin-conjugated detection Abs. | 3 washes | SA-PE \@ 3 ug/ml  | 3 washes | PBS-TBN     |
|                                          |        |                                                 |          |                                     |          |                   |          |             |
|                                          |        | 2 hour incubation                               |          | 1 hour incubation                   |          | 45 min incubation |          | MagPix read |
+------------------------------------------+--------+-------------------------------------------------+----------+-------------------------------------+----------+-------------------+----------+-------------+

**Summary of assay reagents (bio-techne unless specified)**

Complete columns to record bead coupling date and biotin antibody expiry date:

+-------------+--------------------------+---------------------------+-------------+--------------------+-----------+---------------------+----------------------------+----------------------+
| Assay       | Capture antibody on bead | Bead Ab conc (ug/million) | Bead region | Date beads coupled | Antigen   | Biotin detection Ab | Biotin detection Ab expiry | detection Ab (ug/ml) |
+-------------+--------------------------+---------------------------+-------------+--------------------+-----------+---------------------+----------------------------+----------------------+
| **IL8**     | M801 (Thermo)            | **5**                     | 22          |                    | 208-IL    | BAF208              |                            | 1.5                  |
+-------------+--------------------------+---------------------------+-------------+--------------------+-----------+---------------------+----------------------------+----------------------+
| **sTNF-R1** | MAB225                   | **6**                     | 20          |                    | 636-R1    | BAF225              |                            | 1.5                  |
+-------------+--------------------------+---------------------------+-------------+--------------------+-----------+---------------------+----------------------------+----------------------+
| **IL6**     | MAB206                   | **5**                     | 21          |                    | 206-IL    | BAF206              |                            | 1                    |
+-------------+--------------------------+---------------------------+-------------+--------------------+-----------+---------------------+----------------------------+----------------------+
| **Ang2**    | NB110-85467              | **5**                     | 15          |                    | 623-AN    | BAF623              |                            | 1                    |
+-------------+--------------------------+---------------------------+-------------+--------------------+-----------+---------------------+----------------------------+----------------------+
| **Ang1**    | MAB9231                  | **5**                     | 18          |                    | 923-AN    | BAF923              |                            | 1.5                  |
+-------------+--------------------------+---------------------------+-------------+--------------------+-----------+---------------------+----------------------------+----------------------+
| **TRAIL**   | MAB375                   | **6**                     | 25          |                    | 375-TL    | BAF375              |                            | 1                    |
+-------------+--------------------------+---------------------------+-------------+--------------------+-----------+---------------------+----------------------------+----------------------+
| **IL10**    | MAB2172                  | **4**                     | 26          |                    | 1064-IL   | BAF217              |                            | 1.5                  |
+-------------+--------------------------+---------------------------+-------------+--------------------+-----------+---------------------+----------------------------+----------------------+
| **sTREM1**  | H00054210-M04            | **6**                     | 14          |                    | 1278-TR   | BAF1278             |                            | 2                    |
+-------------+--------------------------+---------------------------+-------------+--------------------+-----------+---------------------+----------------------------+----------------------+
| **IP-10**   | MAB266                   | **5**                     | 29          |                    | 266-IP    | BAF266              |                            | 1                    |
+-------------+--------------------------+---------------------------+-------------+--------------------+-----------+---------------------+----------------------------+----------------------+
| **Azu**     | NBP2-12045               | **7**                     | 27          |                    | 2200-SE   | AF2200+B            |                            | 1.5                  |
+-------------+--------------------------+---------------------------+-------------+--------------------+-----------+---------------------+----------------------------+----------------------+
| **MxA**     | MA5-24914 (Thermo)       | **6**                     | 28          |                    | TP307418  | AF7946+B            |                            | 1                    |
|             |                          |                           |             |                    |           |                     |                            |                      |
|             |                          |                           |             |                    | (OriGene) |                     |                            |                      |
+-------------+--------------------------+---------------------------+-------------+--------------------+-----------+---------------------+----------------------------+----------------------+
| **CHI3L1**  | MAB25991                 | **4.5**                   | 30          |                    | 2599-CH   | BAF2599             |                            | 1                    |
+-------------+--------------------------+---------------------------+-------------+--------------------+-----------+---------------------+----------------------------+----------------------+

[**Sample preparation in advance**]{.underline}

1.  Dispense DBS samples into elution plates and record sample ID electronically to correspond with plate name and layout. Dispensed DBS can be sealed and stored as per the original sample storage so that they are ready to be tested in larger batches.

**Day before assay day**

2.  Check that MagPix machine is in working order and that calibration & verification kits and drive fluid are available.

3.  Prepare DBS elution buffer fresh on day of use:

Protease inhibitor: dissolve 1 tablet per 2 ml PBS to give 25X (Sigma, cOmplete, 04693116001)

4.  Combine PBS-TBN with 25X protease inhibitor solution for the number of plates to be run on the day:

|                      |                     |                   |                             |                   |                      |                     |                   |                             |                   |
|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
| **Number of plates** | PBS-TBN volume (ul) | Total volume (ul) | 25X Protease inhibitor (ul) | This many tablets | **Number of plates** | PBS-TBN volume (ul) | Total volume (ul) | 25X Protease inhibitor (ul) | This many tablets |
| **1**                | 8,448               | 8,800             | 352                         | 1                 | **6**                | 50,688              | 52,800            | 2,112                       | 2                 |
| **2**                | 16,896              | 17,600            | 704                         | 1                 | **7**                | 59,136              | 61,600            | 2,464                       | 2                 |
| **3**                | 25,344              | 26,400            | 1,056                       | 1                 | **8**                | 67,584              | 70,400            | 2,816                       | 2                 |
| **4**                | 33,792              | 35,200            | 1,408                       | 1                 | **9**                | 76,032              | 79,200            | 3,168                       | 2                 |
| **5**                | 42,240              | 44,000            | 1,760                       | 1                 | **10**               | 84,480              | 88,000            | 3,520                       | 2                 |

5.  Label black plate(s) with date & plate ID.

6.  Add 100 ul/well of elution buffer to DBS in the low-bind plate that they are in.

7.  Seal with sticky plate cover, label, and place in fridge overnight. Time put in fridge \_\_\_\_\_\_\_\_\_\_\_\_\_\_

[**Assay running day**]{.underline}

8.  Get a box of wet ice, if available.

9.  Retrieve standards from -80 freezer and put on ice or in fridge to thaw.

Tip: Do not re-freeze standards. Use a new aliquot each day.

10. Bring eluted sample plates to ambient temperature & put on a shaker until ready to use. Start time \_\_\_\_\_\_\_\_\_\_\_

11. Prepare beads: get coupled beads from fridge, vortex and sonicate for 30 sec of each.

12.  Add the volume of PBS-TBN to a single tube for the number of plates being run on the day. This allows 7% surplus.

+-------------+-------------------------+-------------------+-------------------------------+
| Plates      | **PBS-TBN volume (uL)** | Total needed (ul) | Bead volume of each bead (ul) |
+-------------+-------------------------+-------------------+-------------------------------+
| 1           |                         | 5,136             | 8.3                           |
+-------------+-------------------------+-------------------+-------------------------------+
| 2           |                         | 10,272            | 16.6                          |
+-------------+-------------------------+-------------------+-------------------------------+
| 3           |                         | 15,408            | 24.9                          |
+-------------+-------------------------+-------------------+-------------------------------+
| 4           |                         | 20,544            | 33.1                          |
+-------------+-------------------------+-------------------+-------------------------------+
| 5           |                         | 25,680            | 41.4                          |
+-------------+-------------------------+-------------------+-------------------------------+
| 6           |                         | 30,816            | 49.7                          |
+-------------+-------------------------+-------------------+-------------------------------+
| 7           |                         | 35,952            | 58.0                          |
+-------------+-------------------------+-------------------+-------------------------------+
| 8           |                         | 41,088            | 66.3                          |
+-------------+-------------------------+-------------------+-------------------------------+
| 9           |                         | 46,224            | 74.6                          |
+-------------+-------------------------+-------------------+-------------------------------+
| 10          | 50,060.4                | 51,360            | 82.8                          |
+-------------+-------------------------+-------------------+-------------------------------+

13. Vortex bead stocks again & add volume of each bead to the tube.

(calculated to get 20k beads/ml \[ie 1000 beads/well). Tick as you add the beads:

+---------+-------+---------+-------+--------+---------+
| €sTNFR1  | €Ang1  | €IL-10   | €IL-6  | €TRAIL  | €IP-10   |
|         |       |         |       |        |         |
| €MxA     | €Ang2  | €sTREM1  | €IL-8  | €Azu    | €CHI3L1  |
+---------+-------+---------+-------+--------+---------+

14. Add [**50 ul**]{.underline} of mixed beads to each well.

15. Wash the beads: put plate on magnet, wait 60 sec, with the plate still firmly on the magent flick out the liquid. Remove plate from magnet to add **100 ul PBST** to each well. Return plate to magnet for 60 sec, flick out wash liquid as before, dab firmly but gently on tissue to remove excess liquid.

16. Vortex & spin down the standards.

17. Add **30 ul per well** of each sample to the black plate.

18. Add **30 ul per well** of each standard in duplicate to the black plate.

19. Cover plates with black cover or foil & incubate on shaker at room temp for 2 hours. Start \_\_\_\_\_\_\_ Ended \_\_\_\_\_\_\_\_

20. During the incubation, prepare biotin detection antibodies:

21. **Detection Abs**: Get aliquots of appropriate size from the freezer, depending on number of plates being run. Fill in expiry dates on table at the start of this protocol.

22. Combine detection antibodies as per Detection Antibody Prep protocol.

Back to the plate when incubation is over....

23. **3** **WASHES** with **100 ul PBST** to each well as before. **NOTE that you should follow your Risk Assessment when disposing of samples.**

24. Add **30 ul/well** of the preopared detection antibody mixture.

25. Cover plates & inclubate on shaker for 60 mins. Start time \_\_\_\_\_\_\_\_\_\_ Ended \_\_\_\_\_\_\_\_\_\_\_

26. During the incubation, prepare SA-PE to be 3 ug/ml from the 1 mg/ml stock. (This includes 10% extra volume to allow multichannel pipetting):

+--------------+-------------------------+-------------------+-----------------------+
| Plates       | **PBS-TBN volume (ml)** | Total needed (ml) | **SA-PE volume (ul)** |
+--------------+-------------------------+-------------------+-----------------------+
| 1            | **3.151**               | 3.160             | **9.5**               |
+--------------+-------------------------+-------------------+-----------------------+
| 2            | **6.301**               | 6.320             | **19.0**              |
+--------------+-------------------------+-------------------+-----------------------+
| 3            | **9.452**               | 9.480             | **28.4**              |
+--------------+-------------------------+-------------------+-----------------------+
| 4            | **12.602**              | 12.640            | **37.9**              |
+--------------+-------------------------+-------------------+-----------------------+
| 5            | **15.753**              | 15.800            | **47.4**              |
+--------------+-------------------------+-------------------+-----------------------+
| 6            | **18.903**              | 18.960            | **56.9**              |
+--------------+-------------------------+-------------------+-----------------------+
| 7            | **22.054**              | 22.120            | **66.4**              |
+--------------+-------------------------+-------------------+-----------------------+
| 8            | **25.204**              | 25.280            | **75.8**              |
+--------------+-------------------------+-------------------+-----------------------+
| 9            | **28.355**              | 28.440            | **85.3**              |
+--------------+-------------------------+-------------------+-----------------------+
| 10           | **31.505**              | 31.600            | **94.8**              |
+--------------+-------------------------+-------------------+-----------------------+

27. 3 WASHES: wash plate 3 times with **100 ul PBST** to each well as before.

28. Add **30 ul/well of SA-PE** dilution across the plate.

29. Cover & incubate for 45 mins on shaker. Start time \_\_\_\_\_\_\_\_\_\_\_ Ended \_\_\_\_\_\_\_\_\_\_\_

30. 3 WASHES: wash 3 times with **100 ul PBST** to each well well as before.

31. Add **100 ul/well of PBS-TBN**.

32. Cover plate and store plate in fridge if reading the next day, or read immediately.

33. On day of reading: mix plate on gentle shaker before putting in the MagPix machine.
