<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Supplementary Material : A multiplex bead-based immunoassay and data analysis pipeline for 12 markers of fever severity in dried blood spots - 5&nbsp; Bead Coupling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs-MAC-C75T46D2VY/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs-MAC-C75T46D2VY/clipboard/clipboard.min.js"></script>
<script src="site_libs-MAC-C75T46D2VY/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs-MAC-C75T46D2VY/quarto-search/fuse.min.js"></script>
<script src="site_libs-MAC-C75T46D2VY/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="Coupling_Confirmation.html" rel="next">
<link href="Capture_Antibody_Prep.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs-PC-37XXCB3/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="Bead_Coupling.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Bead Coupling</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../_book">Supplementary Material : A multiplex bead-based immunoassay and data analysis pipeline for 12 markers of fever severity in dried blood spots</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Overview</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="Marker_List.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">List of Markers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="Buffers_and_Reagents.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Buffers &amp; Reagents</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="Capture_Antibody_Prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Capture Antibody Preparation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="Bead_Coupling.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Bead Coupling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="Coupling_Confirmation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Coupling Confirmation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="Detection_Antibody_Prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Detection Antibody Prep</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="antigens.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Antigens</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="antibody_pairs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Screening antibody pairs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="Cross_Reactivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Cross-reactivity Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="Standards_Prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Standard curves</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="Magpix_Protocol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">MagPix Protocol</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="Coefficients_of_Variation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Coefficients of Variation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="Specimen_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Specimen Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="Analysis_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Data Analysis - A Tutorial based on the Mos-Def study</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Funding &amp; Declarations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="CRediT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">CRediT Framework</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#assay-specific-reagents" id="toc-assay-specific-reagents" class="nav-link active" data-scroll-target="#assay-specific-reagents"><span class="header-section-number">5.1</span> Assay-specific reagents</a></li>
  <li><a href="#other-consumables-reagents-and-equipment-needed." id="toc-other-consumables-reagents-and-equipment-needed." class="nav-link" data-scroll-target="#other-consumables-reagents-and-equipment-needed."><span class="header-section-number">5.2</span> Other consumables, reagents and equipment needed.</a></li>
  <li><a href="#preparation" id="toc-preparation" class="nav-link" data-scroll-target="#preparation"><span class="header-section-number">5.3</span> Preparation</a></li>
  <li><a href="#protocol-a---coupling-beads-for-8-plates" id="toc-protocol-a---coupling-beads-for-8-plates" class="nav-link" data-scroll-target="#protocol-a---coupling-beads-for-8-plates"><span class="header-section-number">5.4</span> Protocol A - Coupling beads for 8 plates</a></li>
  <li><a href="#protocol-b---coupling-beads-for-52-plates" id="toc-protocol-b---coupling-beads-for-52-plates" class="nav-link" data-scroll-target="#protocol-b---coupling-beads-for-52-plates"><span class="header-section-number">5.5</span> Protocol B - Coupling beads for 52 plates</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Bead Coupling</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>We provide two versions of this protocol for coupling enough beads for 8 plates using 120 µL of bead stock (Option A), or a larger-scale coupling which provides enough beads for about 52 plates using 500 µL of bead stock (Option B).</p>
<p>Variations on the number of beads may be calculated using the Luminex Cookbook scaling table.</p>
<section id="assay-specific-reagents" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="assay-specific-reagents"><span class="header-section-number">5.1</span> Assay-specific reagents</h2>
<table class="table">
<colgroup>
<col style="width: 9%">
<col style="width: 19%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Marker</th>
<th>Component</th>
<th>Catalogue #</th>
<th>Supplier</th>
<th>Bead region</th>
<th>µg antibody/million beads</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ang-1</td>
<td>Beads</td>
<td>MC10018-01</td>
<td>Luminex</td>
<td>18</td>
<td>5</td>
</tr>
<tr class="even">
<td>Ang-2</td>
<td>Beads</td>
<td>MC10015-01</td>
<td>Luminex</td>
<td>15</td>
<td>5</td>
</tr>
<tr class="odd">
<td>Azu</td>
<td>Beads</td>
<td>MC10027-01</td>
<td>Luminex</td>
<td>27</td>
<td>7</td>
</tr>
<tr class="even">
<td>CHI3L1</td>
<td>Beads</td>
<td>MC10030-01</td>
<td>Luminex</td>
<td>30</td>
<td>4.5</td>
</tr>
<tr class="odd">
<td>IL-6</td>
<td>Beads</td>
<td>MC10021-01</td>
<td>Luminex</td>
<td>21</td>
<td>5</td>
</tr>
<tr class="even">
<td>IL-8</td>
<td>Beads</td>
<td>MC10022-01</td>
<td>Luminex</td>
<td>22</td>
<td>5</td>
</tr>
<tr class="odd">
<td>IL-10</td>
<td>Beads</td>
<td>MC10026-01</td>
<td>Luminex</td>
<td>26</td>
<td>4</td>
</tr>
<tr class="even">
<td>IP-10</td>
<td>Beads</td>
<td>MC10029-01</td>
<td>Luminex</td>
<td>29</td>
<td>5</td>
</tr>
<tr class="odd">
<td>MxA</td>
<td>Beads</td>
<td>MC10028-01</td>
<td>Luminex</td>
<td>28</td>
<td>6</td>
</tr>
<tr class="even">
<td>sTNFR1</td>
<td>Beads</td>
<td>MC10020-01</td>
<td>Luminex</td>
<td>20</td>
<td>6</td>
</tr>
<tr class="odd">
<td>sTREM-1</td>
<td>Beads</td>
<td>MC10014-01</td>
<td>Luminex</td>
<td>14</td>
<td>6</td>
</tr>
<tr class="even">
<td>TRAIL</td>
<td>Beads</td>
<td>MC10025-01</td>
<td>Luminex</td>
<td>25</td>
<td>6</td>
</tr>
<tr class="odd">
<td>Ang-1</td>
<td>Capture antibody</td>
<td>MAB9231</td>
<td>Bio-techne</td>
<td>18</td>
<td>5</td>
</tr>
<tr class="even">
<td>Ang-2</td>
<td>Capture antibody</td>
<td>NB110-85467</td>
<td>Bio-techne</td>
<td>15</td>
<td>5</td>
</tr>
<tr class="odd">
<td>Azu</td>
<td>Capture antibody</td>
<td>NBP2-12045</td>
<td>Bio-techne</td>
<td>27</td>
<td>7</td>
</tr>
<tr class="even">
<td>CHI3L1</td>
<td>Capture antibody</td>
<td>MAB25991</td>
<td>Bio-techne</td>
<td>30</td>
<td>4.5</td>
</tr>
<tr class="odd">
<td>IL-6</td>
<td>Capture antibody</td>
<td>MAB206</td>
<td>Bio-techne</td>
<td>21</td>
<td>5</td>
</tr>
<tr class="even">
<td>IL-8</td>
<td>Capture antibody</td>
<td>M801 (Thermo)</td>
<td>Bio-techne</td>
<td>22</td>
<td>5</td>
</tr>
<tr class="odd">
<td>IL-10</td>
<td>Capture antibody</td>
<td>MAB2172</td>
<td>Bio-techne</td>
<td>26</td>
<td>4</td>
</tr>
<tr class="even">
<td>IP-10</td>
<td>Capture antibody</td>
<td>MAB266</td>
<td>Bio-techne</td>
<td>29</td>
<td>5</td>
</tr>
<tr class="odd">
<td>MxA</td>
<td>Capture antibody</td>
<td>MA5-24914</td>
<td>Bio-techne</td>
<td>28</td>
<td>6</td>
</tr>
<tr class="even">
<td>sTNFR1</td>
<td>Capture antibody</td>
<td>MAB225</td>
<td>Bio-techne</td>
<td>20</td>
<td>6</td>
</tr>
<tr class="odd">
<td>sTREM-1</td>
<td>Capture antibody</td>
<td>H00054210-M04</td>
<td>Bio-techne</td>
<td>14</td>
<td>6</td>
</tr>
<tr class="even">
<td>TRAIL</td>
<td>Capture antibody</td>
<td>MAB375</td>
<td>Bio-techne</td>
<td>25</td>
<td>6</td>
</tr>
</tbody>
</table>
</section>
<section id="other-consumables-reagents-and-equipment-needed." class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="other-consumables-reagents-and-equipment-needed."><span class="header-section-number">5.2</span> Other consumables, reagents and equipment needed.</h2>
<table class="table">
<colgroup>
<col style="width: 54%">
<col style="width: 17%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Item</th>
<th>Supplier</th>
<th>Catalogue number</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sodium phosphate monobasic (NaH<sub>2</sub>PO<sub>4</sub>)</td>
<td>Sigma</td>
<td></td>
</tr>
<tr class="even">
<td>Sodium hydroxide (NaOH)</td>
<td>Sigma</td>
<td></td>
</tr>
<tr class="odd">
<td>Phosphate buffered saline (PBS)</td>
<td>Sigma</td>
<td></td>
</tr>
<tr class="even">
<td>Sulfo-NHS</td>
<td>Thermo</td>
<td>24510</td>
</tr>
<tr class="odd">
<td>EDC</td>
<td>Thermo</td>
<td>22980</td>
</tr>
<tr class="even">
<td>Protein low-bind microtubes, 1 per coupling</td>
<td>Eppendorf</td>
<td>0030108116/0030108132</td>
</tr>
<tr class="odd">
<td>Pipettes and tips for 10 µL, 200 µL, 1 mL</td>
<td>Any suitable</td>
<td></td>
</tr>
<tr class="even">
<td>0.2 µm syringe filters</td>
<td>Any suitable</td>
<td></td>
</tr>
<tr class="odd">
<td>Syringe, 50 mL, sterile</td>
<td>Any suitable</td>
<td></td>
</tr>
<tr class="even">
<td>50 mL tube, sterile</td>
<td>Any suitable</td>
<td></td>
</tr>
<tr class="odd">
<td>Magnetic tube rack</td>
<td>Invitrogen</td>
<td>CS15000</td>
</tr>
<tr class="even">
<td>End-over-end rotating mixer</td>
<td>Any suitable</td>
<td></td>
</tr>
<tr class="odd">
<td>Fine balance</td>
<td>Any suitable</td>
<td></td>
</tr>
<tr class="even">
<td>pH meter</td>
<td>Any suitable</td>
<td></td>
</tr>
<tr class="odd">
<td>Sonicating waterbath</td>
<td>VWR</td>
<td>142-6044</td>
</tr>
</tbody>
</table>
</section>
<section id="preparation" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="preparation"><span class="header-section-number">5.3</span> Preparation</h2>
<p>This protocol uses EDC [1-ethyl-3-(3-dimethylaminopropyl)carbodiimide hydrochloride)]. EDC absorbs moisture from the air. It is helpful to aliquot it into 50 mg, single-use, amounts in screw cap tubes on receipt and to store these in individual ziplock bags with desiccant, at -20° C.</p>
<p>For quality assurance processes, we recommend keeping note of the lot numbers and expiry dates of both beads and capture antibodies. The diagnostic performance of beads changes with time and we do not recommend using coupled beads that are more than two months old.</p>
</section>
<section id="protocol-a---coupling-beads-for-8-plates" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="protocol-a---coupling-beads-for-8-plates"><span class="header-section-number">5.4</span> Protocol A - Coupling beads for 8 plates</h2>
<p>⌚ Timing: 2 hours, then 2 hours incubation, 1h45m to finish. Total approx. 5h45m.</p>
<p>This protocol takes place at ambient temperature. All incubations are at ambient temperature.</p>
<p><strong>Tip:</strong> Protect beads from light with a foil cover when they are not being manipulated such as during incubations.</p>
<ol type="1">
<li><p>Label tubes (Eppendorf, protein lo-bind) one for each coupling, with at least antigen name and bead region.</p></li>
<li><p>Vortex and sonicate the bead stocks for ~60 seconds of each. Vortex some more immediately before pipetting.</p></li>
<li><p>Transfer 120 µL of bead stock (1.5 x 10<sup>6</sup> beads for 8 full plates) into each respective tube.</p></li>
<li><p>Put tubes in magnet rack for 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>Remove tubes from magnet rack. Add 100 µL dH<sub>2</sub>O. Vortex &amp; sonicate for ~20 s of each.</p></li>
<li><p>Tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>Remove tube from magnet rack. Add 80 µL Activation buffer (0.1 M sodium phosphate, pH 6.2). Vortex &amp; sonicate, ~20 s each.</p></li>
<li><p>Make up 50 mg/mL sulfo-NHS (Thermo, 24510) and 50 mg/mL EDC (Thermo, 22980) in Activation buffer, in separate tubes. Use max 25 mg in 500 µL (for 12 couplings).</p></li>
<li><p>Add 10 µL of the sulfo-NHS solution to the beads. Vortex.</p></li>
<li><p>Add 10 µL of the EDC solution to the beads. Vortex.</p></li>
<li><p>Incubate 10 mins @ room temp. Vortex. Incubate for further 10 mins.</p></li>
<li><p>During the incubation, set up new tubes for Ab dilution in MES buffer.</p></li>
<li><p>To 400 µL MES, minus the volume of Ab, add in this much of each Ab:</p></li>
</ol>
<table class="table">
<colgroup>
<col style="width: 11%">
<col style="width: 30%">
<col style="width: 22%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Antibody on bead</th>
<th>Ab catalogue number (bio-techne unless stated)</th>
<th>Antibody amount per million beads</th>
<th>Volume of capture antibody needed for 1.5e<sup>6</sup> beads (µL)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ang-1</td>
<td>MAB9231</td>
<td>5</td>
<td>7.5</td>
</tr>
<tr class="even">
<td>Ang-2</td>
<td>NB110-85467</td>
<td>5</td>
<td>7.5</td>
</tr>
<tr class="odd">
<td>Azu</td>
<td>NBP2-12045</td>
<td>7</td>
<td>10.5</td>
</tr>
<tr class="even">
<td>CHI3L1</td>
<td>MAB25991</td>
<td>4.5</td>
<td>6.8</td>
</tr>
<tr class="odd">
<td>IL-6</td>
<td>MAB206</td>
<td>5</td>
<td>7.5</td>
</tr>
<tr class="even">
<td>IL-8</td>
<td>M801 (Thermo)</td>
<td>5</td>
<td>7.5</td>
</tr>
<tr class="odd">
<td>IL-10</td>
<td>MAB2172</td>
<td>4</td>
<td>6.0</td>
</tr>
<tr class="even">
<td>IP-10</td>
<td>MAB266</td>
<td>5</td>
<td>7.5</td>
</tr>
<tr class="odd">
<td>MxA</td>
<td>MA5-24914 (Thermo)</td>
<td>6</td>
<td>9.0</td>
</tr>
<tr class="even">
<td>sTNF-R1</td>
<td>MAB225</td>
<td>6</td>
<td>9.0</td>
</tr>
<tr class="odd">
<td>sTREM1</td>
<td>H00054210-M04</td>
<td>6</td>
<td>9.0</td>
</tr>
<tr class="even">
<td>TRAIL</td>
<td>MAB375</td>
<td>6</td>
<td>9.0</td>
</tr>
</tbody>
</table>
<ol start="16" type="1">
<li><p>Set these Ab tubes aside and continue with the beads.</p></li>
<li><p>Bead tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>MES wash 1: Remove tube from magnet rack. Add 250 µL MES buffer. Vortex &amp; sonicate for ~ 20 s each.</p></li>
<li><p>Tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>MES wash 2: Remove tube from magnet rack. Add 250 µL MES buffer. Vortex &amp; sonicate for ~ 20 s each.</p></li>
<li><p>Tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>Add 100 µL MES buffer to each bead tube.</p></li>
<li><p>Transfer 400 µL of each antibody dilution into the respective bead tubes and vortex.</p></li>
<li><p>Incubate 2 hours on mixer at room temp. Start time _______________</p></li>
<li><p>Tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>Remove tube from magnet rack. Add 500 µL PBS-TBN. Vortex &amp; sonicate for ~20 s.</p></li>
<li><p>Tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>PBS-TBN wash 1: Remove tube from magnet rack. Add 1 mL PBS-TBN. Vortex &amp; sonicate for ~20 s.</p></li>
<li><p>Tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>PBS-TBN wash 2: Remove tube from magnet rack. Add 1 mL PBS-TBN. Vortex &amp; sonicate for ~20 s.</p></li>
<li><p>Tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>Remove tube from magnet rack. Resuspend coupled beads in 200 µL PBS-TBN. Vortex.</p></li>
<li><p>Ensure newly coupled beads are fully labelled.</p></li>
<li><p>Store the coupled beads in the fridge.</p></li>
</ol>
</section>
<section id="protocol-b---coupling-beads-for-52-plates" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="protocol-b---coupling-beads-for-52-plates"><span class="header-section-number">5.5</span> Protocol B - Coupling beads for 52 plates</h2>
<p>⌚ Timing: 2 hours, then 2 hours incubation, 1h45m to finish. Total approx. 5h45m.</p>
<p>The protocol takes place at ambient temperature. All incubations are at ambient temperature.</p>
<ol type="1">
<li><p>Label tubes (Eppendorf, protein lo-bind) one for each coupling.</p></li>
<li><p>Vortex and sonicate the bead stocks for ~60 s of each. Vortex some more immediately before pipetting.</p></li>
<li><p>Transfer 0.5 mL of bead stock (6.25 x 106 beads for ~52 full plates) into each respective tube.</p></li>
<li><p>Put tube in magnet rack for 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>Remove tube from magnet rack. Add 100 µL dH<sub>2</sub>O. Vortex &amp; sonicate for ~20 s of each.</p></li>
<li><p>Tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>Remove tube from magnet rack. Add 80 µL Activation buffer. Vortex &amp; sonicate, ~20 s each.</p></li>
<li><p>In separate tubes, make up 50 mg/mL sulfo-NHS and 50 mg/mL EDC in Activation buffer. These should always be made fresh, immediately before use, and not stored.</p></li>
<li><p>Add 10 µL of the sulfo-NHS solution to the beads. Vortex.</p></li>
<li><p>Add 10 µL of the EDC solution to the beads. Vortex.</p></li>
<li><p>Incubate 10 mins @ room temp. Vortex. Incubate for further 10 mins.</p></li>
<li><p>During the incubation, set up 1.5 mL tubes for antibody dilution in MES buffer. One tube per bead region.</p></li>
<li><p>Dispense 400 µL MES to each tube.</p></li>
<li><p>Remove the MES volume indicated for each Ab in the table below (bold numbers).</p></li>
<li><p>Add in the indicated amount of Ab stock:</p></li>
</ol>
<table class="table">
<colgroup>
<col style="width: 11%">
<col style="width: 30%">
<col style="width: 22%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Antibody on bead</th>
<th>Ab catalogue number (bio-techne unless stated)</th>
<th>Antibody amount per million beads</th>
<th>Volume of capture antibody needed for 1.5e<sup>6</sup> beads (µL)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ang-1</td>
<td>MAB9231</td>
<td>5</td>
<td>31.3</td>
</tr>
<tr class="even">
<td>Ang-2</td>
<td>NB110-85467</td>
<td>5</td>
<td>31.3</td>
</tr>
<tr class="odd">
<td>Azu</td>
<td>NBP2-12045</td>
<td>7</td>
<td>43.8</td>
</tr>
<tr class="even">
<td>CH3L1</td>
<td>MAB25991</td>
<td>4.5</td>
<td>28.1</td>
</tr>
<tr class="odd">
<td>IL-6</td>
<td>MAB206</td>
<td>5</td>
<td>31.3</td>
</tr>
<tr class="even">
<td>IL-8</td>
<td>M801 (Thermo)</td>
<td>5</td>
<td>31.3</td>
</tr>
<tr class="odd">
<td>IL-10</td>
<td>MAB2172</td>
<td>4</td>
<td>25.0</td>
</tr>
<tr class="even">
<td>IP-10</td>
<td>MAB266</td>
<td>5</td>
<td>31.3</td>
</tr>
<tr class="odd">
<td>MxA</td>
<td>MA5-24914 (Thermo)</td>
<td>6</td>
<td>37.5</td>
</tr>
<tr class="even">
<td>sTNF-R1</td>
<td>MAB225</td>
<td>6</td>
<td>37.5</td>
</tr>
<tr class="odd">
<td>sTREM1</td>
<td>H00054210-M04</td>
<td>6</td>
<td>37.5</td>
</tr>
<tr class="even">
<td>TRAIL</td>
<td>MAB375</td>
<td>6</td>
<td>37.5</td>
</tr>
</tbody>
</table>
<p>Set these Ab tubes aside and continue with the beads….</p>
<ol start="18" type="1">
<li><p>Bead tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>MES wash 1: Remove tube from magnet rack. Add 500 µL MES buffer. Vortex &amp; sonicate for ~ 20 s each.</p></li>
<li><p>Tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>MES wash 2: Remove tube from magnet rack. Add 500 µL MES buffer. Vortex &amp; sonicate for ~ 20 s each.</p></li>
<li><p>Tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>Add 100 µL MES buffer to beads.</p></li>
<li><p>Transfer all 400 µL of each antibody dilution into the respective bead tubes and vortex. (So the antibody amount is eventually diluted in 0.5 mL of MES by the time it is incubated with the beads, as per scale-up table).</p></li>
<li><p>Incubate 2 hours on mixer at room temp. Start time _______________</p></li>
<li><p>Tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>Remove tube from magnet rack. Add 0.5 mL PBS-TBN. Vortex &amp; sonicate for ~20 s.</p></li>
<li><p>Tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>PBS-TBN wash 1: Remove tube from magnet rack. Add 1 mL PBS-TBN. Vortex &amp; sonicate for ~20 s.</p></li>
<li><p>Tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>PBS-TBN wash 2: Remove tube from magnet rack. Add 1 mL PBS-TBN. Vortex &amp; sonicate for ~20 s.</p></li>
<li><p>Tube into magnet rack, 60 s.</p></li>
<li><p>Remove supernatant without disturbing beads.</p></li>
<li><p>Remove tube from magnet rack. Resuspend coupled beads in 830 µL PBS-TBN. Vortex. This is 1.66x the original volume (500 µL) to give a theoretical count of 7.5 x 10<sup>6</sup> beads/mL.</p></li>
<li><p>Fully label and store the newly coupled beads in the fridge.</p></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="Capture_Antibody_Prep.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Capture Antibody Preparation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="Coupling_Confirmation.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Coupling Confirmation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>